coverage:
  status:
    project:
      default: off
      unittests:
        enabled: true
        target: 55%
        threshold: null
        base: auto
        flags: unittests
      karma:
        enabled: true
        target: 91%
        threshold: null
        base: auto
        flags: karma
    patch:
      default: off
      unittests:
        enabled: true
        target: 55%
        threshold: null
        base: auto
        flags: unittests
      karma:
        enabled: true
        target: 91%
        threshold: null
        base: auto
        flags: karma