coverage:
  status:
    project:
      default: off
      unittests:
        enabled: true
        target: 80%
        threshold: null
        base: auto
        flags: unittests
      karma:
        enabled: true
        target: 90%
        threshold: null
        base: auto
        flags: karma
      jest:
        enabled: true
        target: 36%
        threshold: null
        base: auto
        flags: jest
    patch:
      default: off
      unittests:
        enabled: true
        target: 80%
        threshold: null
        base: auto
        flags: unittests
      karma:
        enabled: true
        target: 90%
        threshold: null
        base: auto
        flags: karma
      jest:
        enabled: true
        target: 50%
        threshold: null
        base: auto
        flags: jest
flags:
  unittests:
    paths:
      - bundles/core/
  karma:
    paths:
      - ui.apps/
  jest:
    paths:
      - react-components/
